version: "3.8"
services:
  speedtest:
    build: ./speedtest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 9000:9000
    environment:
      - "TITLE=LibreSpeed"
      - "MODE=frontend"
      - "PASSWORD=password"
      - "TELEMETRY=true"
      - "ENABLE_ID_OBFUSCATION=true"
      - "REDACT_IP_ADDRESSES=false"
    depends_on:
      - fluentd
      - mysql
    volumes:
      - ./speedtest/servers.json:/servers.json
      - ./speedtest/docker/default.conf:/etc/nginx/conf.d/default.conf
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: speedtest.access

  mysql:
    image: mysql:8.0
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
      - ./speedtest/results/telemetry_mysql.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=speed_db
      - MYSQL_ROOT_PASSWORD=pass
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: mysql.access

  caddy:
    image: caddy:2.4.5
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 8080:8080
      - 80:80
    depends_on:
      - fluentd
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: caddy.access

  elasticsearch:
    image: elasticsearch:7.14.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    deploy:
      restart_policy:
        condition: on-failure

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - 24224:24224
      - 24224:24224/udp
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "5"

  kibana:
    image: kibana:7.14.1
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    deploy:
      resources:
        limits:
          memory: 512m
      restart_policy:
        condition: on-failure
    ports:
      - 5601:5601

volumes:
  dbdata: